### ISSUE TITLE
fontpresentation.js is adding inner styles into html

### ISSUE THREAD

**Issue by nbuso** [ebiwd/EBI-Pattern-library#15]
Hii,

this file:
http://ebiwd.github.io/EBI-Framework/js/fontpresentation.js
is adding inner styles in the html breaking our pages.

is this script meant to be included in our html? or is it meant to be used in specific contexts?

**Comment by khawkins98** [comment]
Hi, is the page that's having problems available publicly, or can you show some details of what's happening?

You don't have to use the fonts js, but obviously we'd like to track down any conflicts.

**Comment by nbuso** [comment]
No unfortunately I'm working locally to update to the new visual framework and is not public. In any case the problematic for now is:
input {
display: none;
}
obviously I need to override it everywhere I need an input

**Comment by khawkins98** [comment]
Actually, just remove fontpresentation.js 

This file wasn't meant to be included and wasn't included in most examples, but did make into the auto migration script.

Sorry for the confusion, but thanks for the heads up.
