### ISSUE TITLE
Adjusting the width of the local search input field

### ISSUE THREAD

**Issue by tschaka1904** [ebiwd/EBI-Pattern-library#19]
Refrence: /patterns/search/

Are they any guidelines about the local search search box?

**Comment by khawkins98** [comment]
The one that you saw on https://ebiwd.github.io/EBI-Pattern-library/patterns/search/ is the most general:

![image](https://cloud.githubusercontent.com/assets/928100/19972361/b1693f7e-a1d9-11e6-91de-4fa25b8226dd.png)

We're looking to document others — is there a particular type of functionality you're looking for that's not in the basic example?

**Comment by tschaka1904** [comment]
I was wondering if I'm bound to this search box or if I can modify it a bit. Like making it a little wider, for the local search. Something like the UniProt search.

**Comment by khawkins98** [comment]
Ah, ok. 

The search box now uses the [Foundation grid classes](http://foundation.zurb.com/sites/docs/grid.html) and will stretch to the width of the parent, so if you just change the wrapper class from `medium-6` to `medium-9`, you get: 

![image](https://cloud.githubusercontent.com/assets/928100/20012387/e68623e8-a2a6-11e6-8b69-508e1e9b15b9.png)
