### ISSUE TITLE
Document horizontal secondary navigation pattern

### ISSUE THREAD

**Issue by pesseat** [ebiwd/EBI-Pattern-library#24]
Refrence: /meta-patterns/page-structure/

It would be nice to have an example code for the secondary menu as we don't really know which css classes to keep/remove  from the main EBI template example link (e.g. is leaf class needed for li elements?):
``` html
<div class="menu-block-wrapper menu-block-4 menu-name-main-menu parent-mlid-0 menu-level-3">
  <ul class="menu menu-tree-menu"><li class="first leaf has-children menu-mlid-3057"><a href="/about/leadership" title="Leadership and guidance structure">Leadership</a></li>
    <li class="leaf menu-mlid-3075"><a href="/about/funding" title="Funding of EMBL-EBI">Funding</a></li>
    <li class="leaf menu-mlid-3079"><a href="/about/background" title="History of EMBL-EBI">Background</a></li>
    <li class="leaf menu-mlid-3076"><a href="/about/collaborations" title="EMBL-EBI partnerships">Collaborations</a></li>
    <li class="leaf menu-mlid-14438"><a href="/about/our-impact" title="Impact: reports, facts and figures">Our impact</a></li>
    <li class="last leaf has-children menu-mlid-14440"><a href="/about/women-in-science">Women in Science</a></li>
  </ul>
</div>
```

**Comment by khawkins98** [comment]
Good point. These secondary menus aren't — as of this moment — an officially blessed pattern. 

<img width="785" alt="screen shot 2017-03-08 at 12 39 36" src="https://cloud.githubusercontent.com/assets/928100/23704346/564422f0-03fc-11e7-8b99-691b3aaf069c.png">

They evolved as right-sidebar navigation wasn't very effective, nor did it help indicate the breadcrumb structure.

So, a couple things:
1) Need to revisit this and distill a pattern
2) Make usage rules (when to have horiz at top of page vs right sidebar vertical)

But, to your comment, the `.leaf` class isn't necessary, that's a class that Drupal is injecting  by default. Key bit of code/structure is in [ebi-global.css@481](https://github.com/ebiwd/EBI-Framework/blob/v1.1/css/ebi-global.css#L481):  

``` css
  ul.menu.secondary-menu li,
  .secondary-menu ul.menu li {
    display: inline-block; }

```

**Comment by khawkins98** [comment]
This is now documented: http://www.ebi.ac.uk/style-lab/websites/patterns/menu.html
