### ISSUE TITLE
Some v1.2 css breaks header 

### ISSUE THREAD

**Issue by tschaka1904** [ebiwd/EBI-Pattern-library#32]
Hi, 

was there any major change around last week? My css is playing a bit wild since last week. Here a few pictures: 

![screen shot 2017-05-02 at 12 17 40](https://cloud.githubusercontent.com/assets/5269116/25615896/a8759012-2f31-11e7-9d20-dd02e28f969e.png)
![screen shot 2017-05-02 at 12 17 25](https://cloud.githubusercontent.com/assets/5269116/25615897/a875af20-2f31-11e7-8d36-0e59bc00c1f9.png)

I played a bit with the imported css and set them first back v.1.1 and this did the trick. Everything worked again. Then I could pinpoint it down to two css-files, which seem to break it: 

- https://www.ebi.ac.uk/web_guidelines/EBI-Framework/v1.2/css/ebi-global.css
- https://www.ebi.ac.uk/web_guidelines/EBI-Framework/v1.2/css/theme-embl-petrol.css

**Comment by khawkins98** [comment]
Hi Max, this is due to a change to better support things like Angular ( https://github.com/ebiwd/EBI-Framework/issues/80#issuecomment-295744397 ). 

Framework Clinic is happening now ('til 13.00 in the Ickleton Room if you're free).

**Comment by khawkins98** [comment]
Closing this one out -- please shout if you still need assistance/have an issue.
