### ISSUE TITLE
'Masthead compact' v1.2 page not responsive

### ISSUE THREAD

**Issue by elisabetb** [ebiwd/EBI-Pattern-library#33]
Refrence: /meta-patterns/masthead-compact

Hi, we have used the masthead-compact header, but after updating to the new version 1.2 we realised that the page is not responsive when we resized the window. Is this something you are still working on?

**Comment by khawkins98** [comment]
This should be responsive. Here's a sample page: https://ebiwd.github.io/EBI-Pattern-library/sample-site-v1.2/boilerplate/search-results.html

Is your page somewhere I can have a look at?

**Comment by elisabetb** [comment]
So, without using the compact header, the resizing is responsive like this http://www.ebi.ac.uk/gxa/home . Note that when you resize the navigation links collapse into "Also in this section" dropdown. But when we use the compact header, that doesn't happen and all the navigation links are visible (please see the attached screenshot)

[compact-header.pdf](https://github.com/ebiwd/EBI-Pattern-library/files/1047381/compact-header.pdf)

**Comment by alfonsomunozpomer** [comment]
@khawkins98 We have disabled it in production for the time being. You can see that the menu items overflow into more than one line, whereas the regular masthead groups the overflowing itmes into a drop-down select. See image below for comparison.

<img width="473" alt="image" src="https://cloud.githubusercontent.com/assets/4425744/26722311/41b9a87c-4787-11e7-95b5-eba661743129.png">

**Comment by elisabetb** [comment]
We will post it online

**Comment by elisabetb** [comment]
Here you can see the page code, instead of the screenshot
https://elisabetb.github.io/Compactheader/index.html

**Comment by khawkins98** [comment]
So the "responsive" dropdown menu expects the `ul` classes to be `dropdown menu float-left`. It's the `float-left` you're missing.

And some of you responsive grid classes might also be causing issues, here's the structure I'd suggest:

```html
<div class="masthead-inner row expanded">
    <div class="class="medium-7 large-4 columns"" id="local-title">
        <a href="http://localhost:8080/gxa/home/" title="Back to Expression Atlas homepage">
            <h1>Expression Atlas</h1>
        </a>
    </div>

    <div class=" medium-5 large-push-5 large-3 columns">
        <form id="local-search" name="local-search" method="get" action="http://localhost:8080/gxa/search">
            <fieldset>...</fieldset>
        </form>
    </div>

    <nav class="large-pull-3 large-5 columns">
        <ul class="dropdown menu float-left" data-description="navigational">
            <li>...</li>
        </ul>
    </nav>
</div>
``` 

In general I think you'll want to the menu to come last in the html, and then use foundation's push/pull classes to rejig for large screen.

**Comment by elisabetb** [comment]
Ok thanks, I will try to change it as you propose and let you know 

Thank you very much
